name: Android CI with fir.im (Debug APK)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 设置 JDK 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 确保 Gradle Wrapper 可执行
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      # 构建 Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 调试 APK 文件路径
      - name: Debug APK Path
        run: ls -l app/build/outputs/apk/debug/

      # 上传 Debug APK 到 fir.im
      - name: Upload Debug APK to Fir.im
        run: |
          curl -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
               -F "token=${{ secrets.FIR_TOKEN }}" \
               https://upload.qiniu.com
