name: Android CI with fir.im

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 设置 JDK 环境
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 确保 Gradle Wrapper 可执行
      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      # 上传签名文件
      - name: Setup Keystore
        run: |
          mkdir -p ~/.android
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ~/.android/keystore.jks

      # 构建带签名的 Release APK
      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace

      # 调试 APK 文件路径
      - name: Debug APK Path
        run: ls -l app/build/outputs/apk/release/

      # 上传 APK 到 fir.im
      - name: Upload APK to Fir.im
        run: |
          curl -F "file=@app/build/outputs/apk/release/app-release.apk" \
               -F "token=${{ secrets.FIR_TOKEN }}" \
               https://upload.qiniu.com
